default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: 'root'
  password: 'password'
  host: 172.20.0.2
  port: 3306

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
